# Generated by Django 4.1.7 on 2023-08-31 00:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+11111111111",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
