# Generated by Django 4.1.7 on 2023-09-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="default_photos/profile.png",
                upload_to="",
                verbose_name="Profile Photo",
            ),
        ),
    ]
