#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -o errexit

# Exit immediately if an undeclared variable is used.
set -o pipefail

# Exit immediately if any statement returns a non-true return value.
set -o nounset

# Migrates any database changes.
python manage.py migrate --no-input

# Collect static files.
python manage.py collectstatic --no-input

# Start server.
exec python manage.py runserver 0.0.0.0:8000
