[tool.black]
line-length = 128
target-version = ["py310"]
extend-exclude = '''
(
    /(
        \.eggs
        | \.git
        | \.mypy_cache
        | \.config
        | \.tox
        | \.venv
        | env
        | venv
        | build
    )/
)
'''

[tool.isort]
profile = "black"

[tool.flake8]
ignore = "E203, W503"
max-line-length = 128
