version: "3.9"

services:
  api:
    depends_on:
      - postgres
      - mailhog
    build:
      context: ../../
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - ../../:/app:z
      - static_volume:/app/src/project/staticfiles
      - media_volume:/app/src/project/mediafiles
    expose:
      - "8000"
    env_file:
      - ../../.config/local/django.env
      - ../../.config/local/postgres.env
    command: /start
    networks:
      - techread

  postgres:
    build:
      context: ../../
      dockerfile: ./docker/local/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - ../../.config/local/postgres.env
    networks:
      - techread

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - techread

  nginx:
    restart: always
    depends_on:
      - api
    build:
      context: ../../
      dockerfile: ./docker/local/nginx/Dockerfile
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8080:80"
    networks:
      - techread

networks:
  techread:
    driver: bridge

volumes:
  static_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: src/project/staticfiles
  media_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: src/project/mediafiles
  postgres_data: {}
  postgres_data_backups: {}
