version: "3.9"

services:
  techread:
    build:
      context: ../../
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - ../../:/app:z
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - ../../.config/local/django.env
      - ../../.config/local/postgres.env
    depends_on:
      - postgres
      - mailhog
    command: /start
    networks:
      - techread

  postgres:
    build:
      context: ../../
      dockerfile: ./docker/local/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - ../../.config/local/postgres.env
    networks:
      - techread

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - techread

networks:
  techread:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data: {}
  postgres_data_backups: {}
