#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -o errexit

# Exit immediately if an undeclared variable is used.
set -o pipefail

# Exit immediately if any statement returns a non-true return value.
set -o nounset

working_dir="$(dirname ${0})"

source "${working_dir}/bin/constants"
source "${working_dir}/bin/messages"

message_welcome "Backing up the '${POSTGRES_DB}' database..."

if [[ "${POSTGRES_USER}" == "postgres" ]]; then
  message_error "Backing up as 'postgres' user is not allowed. Please assign 'POSTGRES_USER' env and try again."
  exit 1
fi

export PGHOST="${POSTGRES_HOST}"
export PGPORT="${POSTGRES_PORT}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}"

backup_filename="${BACKUP_PREFIX}_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"

pg_dump | gzip > "${BACKUP_DIR}/${backup_filename}"

message_success "'${POSTGRES_DB}' database backed up to '${BACKUP_DIR}/${backup_filename}'."
