# Generated by Django 4.1.7 on 2023-09-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.TextField(default="", verbose_name="Article Description"),
            preserve_default=False,
        ),
    ]
