# Generated by Django 4.1.7 on 2023-09-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_banner_image_alter_article_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                default="default_photos/article.png",
                null=True,
                upload_to="",
                verbose_name="Banner Image",
            ),
        ),
    ]
