# Generated by Django 4.1.7 on 2023-09-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_clap_article_claps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clap",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
