# Generated by Django 4.1.7 on 2023-09-02 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0006_alter_clap_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="claps",
        ),
        migrations.AlterField(
            model_name="clap",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claps",
                to="articles.article",
            ),
        ),
        migrations.AlterField(
            model_name="clap",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
